### ISSUE TITLE
Link to paper?

### ISSUE THREAD

**Issue by heethesh** [PRBonn/kissicp#1]
Is it on arXiv yet? Thanks!

**Comment by benemer** [comment]
Hey @heethesh, thank you for your interest. We will upload the paper together with the code on October 1st. Stay tuned!

**Comment by alexpoz** [comment]
Hi, would love to read the paper, is it available yet? Thanks!

**Comment by heethesh** [comment]
@alexpoz I see that it's online on arXiv now

**Comment by nachovizzo** [comment]
The preprint version is now available at https://arxiv.org/pdf/2209.15397.pdf
